defmodule AshEx4pm.Activity do
  @moduledoc """
  One `activity :name, on: :action` entity inside an `ex4pm do ... end`
  block. Mirrors the plain-struct DSL entity shape `ash_r2rml`'s
  `AshR2RML.Resource` uses for its own entities
  (`~/ash_r2rml/lib/ash_r2rml/resource.ex:68-102`) -- a real struct, not
  an anonymous map.

  `resource` is filled in automatically by `AshEx4pm.Transformers.Persist`
  when this entity is declared inside a resource's own `ex4pm do ... end`
  block (never set explicitly there); it must be supplied explicitly when
  the entity is declared at the domain level. This is the real
  `AshAi.Transformers.ResourceTools` context-normalization pattern
  (`~/xaas/deps/ash_ai/lib/ash_ai/transformers/resource_tools.ex:13-55,125-127`),
  reused here via `ash-extension-core-pack` v26.9.10's `aex:contextNormalize`
  vocabulary.
  """
  @enforce_keys [:name, :on]
  defstruct [
    :name,
    :on,
    :resource,
    qualifier: "primary",
    __identifier__: nil,
    __spark_metadata__: nil
  ]

  @type t :: %__MODULE__{
          name: atom(),
          on: atom(),
          resource: module() | nil,
          qualifier: String.t() | atom()
        }
end

defmodule AshEx4pm.Dsl do
  @moduledoc "Real `Spark.Dsl.Entity`/`Spark.Dsl.Section` definitions for `ex4pm do ... end`."

  @activity %Spark.Dsl.Entity{
    name: :activity,
    describe: "Declares a single OCEL activity emitted for one Ash action.",
    args: [:name, {:optional, :on}],
    target: AshEx4pm.Activity,
    identifier: :name,
    schema: [
      name: [
        type: :atom,
        required: true,
        doc: "The OCEL activity name this Ash action emits, e.g. :order_created."
      ],
      on: [
        type: :atom,
        required: true,
        doc:
          "The Ash action name (e.g. :create) that triggers this activity. Always " <>
            "required -- there is no implicit per-action inference; see " <>
            "AshEx4pm.Activity's @enforce_keys, which mirrors this requirement."
      ],
      resource: [
        type: :atom,
        required: false,
        doc:
          "The Ash resource this activity applies to. Set automatically by " <>
            "AshEx4pm.Transformers.Persist for resource-level declarations; required " <>
            "explicitly for domain-level declarations. Setting it explicitly at the " <>
            "resource level is a compile error (see AshEx4pm.Transformers.Persist)."
      ],
      qualifier: [
        type: {:or, [:string, :atom]},
        required: false,
        default: "primary",
        doc:
          "The OCEL 2.0 relationship qualifier attached to this activity's single " <>
            "event-to-object relationship (AshEx4pm.Notifier.build_envelope/2's " <>
            "\"relationships\" => [%{\"qualifier\" => ...}] entry). Defaults to " <>
            "\"primary\" for backward compatibility with existing declarations. Set " <>
            "it to a semantically meaningful role (e.g. :orderer, :payer, \"shipped_to\") " <>
            "when the downstream ex4pm engine's e2o/o2o query predicates " <>
            "(Ex4pm.Cognition.Ocpq) need to distinguish this relationship from other " <>
            "activities' relationships on the same object type. Still scoped to " <>
            "one qualifier per activity -- see this notifier's own moduledoc " <>
            "\"Scope: single-object events only\" section for the multi-relationship " <>
            "escape hatch."
      ]
    ]
  }

  @ex4pm %Spark.Dsl.Section{
    name: :ex4pm,
    describe: "Declares which Ash actions emit real OCEL 2.0 events via ex4pm.",
    entities: [@activity],
    schema: [
      provenance_source: [
        type: :atom,
        required: false,
        default: :ash_ex4pm,
        doc:
          "Tagged into every emitted event's metadata.source field " <>
            "(Ex4pm.Event.metadata), so events generated by this extension are " <>
            "distinguishable from hand-constructed or other-source events."
      ]
    ]
  }

  def section, do: @ex4pm
end
