# GENERATED by ggen_igniter from ex4pm's admitted ex4pmb:AdmittedBeam4pmService
# graph (the planning-typed subset). Do not edit.
defmodule AshEx4pm.Ferroplan do
  @moduledoc """
  Thin delegate exposing ex4pm's admitted ferroplan planning capabilities to
  Ash resource authors, generated from the SAME
  `ex4pmb:AdmittedBeam4pmService` graph `Ex4pm.Engine.Beam4pm` itself is
  generated from (ex4pm's `priv/ontology/ex4pm.ttl`, queried from this
  repo's packaged `ex4pm` dependency -- see
  `lib/mix/tasks/ash_ex4pm.ggen.sync.ex`). No ontology fork, no independent
  contract: adding a new planning capability here means adding a new
  `ex4pmb:AdmittedBeam4pmService` individual (with a bound
  `ex4pmb:planningType`) in ex4pm's ontology, cutting a new ex4pm release,
  bumping this repo's `{:ex4pm, ...}` pin, and re-running
  `mix ash_ex4pm.ggen.sync` -- never hand-written dispatch code here.

  Generated functions:

      * `ferroplan_fond_policy/2` -> `Ex4pm.Engine.Beam4pm.execute(:ferroplan_fond_policy, subject, opts)` (planning type `Fond`) (forward_declared)
    * `ferroplan_hierarchical_plan/2` -> `Ex4pm.Engine.Beam4pm.execute(:ferroplan_hierarchical_plan, subject, opts)` (planning type `Hierarchical`) (forward_declared)

  ## Honest status

  Every function here ultimately depends on `Ex4pm.Engine.Beam4pm`'s own
  admitted route table. A `(forward_declared)` capability above refuses
  with `:beam4pm_route_not_live` until beam4pm mounts the matching
  `json_api` route -- see `Ex4pm.Engine.Beam4pm`'s own moduledoc for the
  full disclosure.
  """

  @doc """
  Delegates to `Ex4pm.Engine.Beam4pm.execute(:ferroplan_fond_policy, subject, opts)` --
  ferroplan's Fond planning capability, admitted as an
  ex4pmb:AdmittedBeam4pmService individual. Status: `forward_declared`.
  """
  @spec ferroplan_fond_policy(map(), keyword()) ::
          {:ok, Ex4pm.Engine.Result.t()} | {:error, Ex4pm.Refusal.t()}
  def ferroplan_fond_policy(subject, opts \\ []) do
    Ex4pm.Engine.Beam4pm.execute(:ferroplan_fond_policy, subject, opts)
  end

  @doc """
  Delegates to `Ex4pm.Engine.Beam4pm.execute(:ferroplan_hierarchical_plan, subject, opts)` --
  ferroplan's Hierarchical planning capability, admitted as an
  ex4pmb:AdmittedBeam4pmService individual. Status: `forward_declared`.
  """
  @spec ferroplan_hierarchical_plan(map(), keyword()) ::
          {:ok, Ex4pm.Engine.Result.t()} | {:error, Ex4pm.Refusal.t()}
  def ferroplan_hierarchical_plan(subject, opts \\ []) do
    Ex4pm.Engine.Beam4pm.execute(:ferroplan_hierarchical_plan, subject, opts)
  end
end
